### ISSUE TITLE
Import problem

### ISSUE THREAD

**Issue by phineas0fog** [cpitclaudel/monospacifier#10]
Hello :)
When I launch the python script, I have the following error: `ImportError: No module named fontforge`...
But fontforge is installed, and I have no errors when I try `import fontforge` in ptpython...
I use Manjaro.
Thanks :)

**Comment by cpitclaudel** [comment]
Hi,

I don't know what ptpython and Manjaro are.  Can you `import fontforge` in a plain python session?

**Comment by phineas0fog** [comment]
Manjaro is a GNU/Linux distrib based on arch and ptpython is a python interpreter for Linux :)
And if i run a script with 
    #!/bin/python
    import fontforge
    print(fontforge.version())
The version (20170320) is displayed, so yes, fontforge is installed and he can be binded

**Comment by cpitclaudel** [comment]
Try with

```
#!/bin/python2
import fontforge
print(fontforge.version())
```

instead. Does it raise an error?

**Comment by phineas0fog** [comment]
Thats doesnt work.
-----
But I solve the problem ! At the line 185, ie `print "!!!", fallback.fontname, "!!!", reference.fontname, "!!!"`, I and the parentheses around print's argument, and I change the shebang to `#!/bin/python` and all is working :)

**Comment by cpitclaudel** [comment]
Right, exactly :) You installed fontforge for python3, but the script was in python2 syntax.  Glad you got it working!

**Comment by phineas0fog** [comment]
Oh okay, I don't there is a version for python3 and a vers for python2 :)
