### ISSUE TITLE
Feature request: Full-width characters

### ISSUE THREAD

**Issue by Densaugeo** [cpitclaudel/monospacifier#11]
How difficult would it be to generate fonts with half-width characters monospacified, and full-width characters set to exactly double their width?

I am not sure how to distinguish between half- and full-width characters programmatically. Is the difference specified in Unicode, or does each font decide which characters are which width?

**Comment by cpitclaudel** [comment]
Woops, I missed this post.

It shouldn't be too too hard.  There's this (http://www.unicode.org/reports/tr11-3/), and corresponding code at (https://stackoverflow.com/questions/15114303/determine-whether-a-unicode-character-is-fullwidth-or-halfwidth-in-c) — it's a unicode thing.

You'd impleemnt a new scaler class to wrap your favorite one, and you'd check the corresponding Unicode tabled to decide which reference width to use.

**Comment by cpitclaudel** [comment]
Closing this; feel free to reopen if you need further help!
