### ISSUE TITLE
Roboto Mono and Consolas font fallback chains

### ISSUE THREAD

**Issue by kiwi0fruit** [cpitclaudel/monospacifier#14]
[Here](https://github.com/kiwi0fruit/sugartex#atom-editor-with-full-unicode-support) are best fallback chains for my liking (for Roboto Mono and Consolas).

~I think that creating a single font is too restricting because of the different FOSS font licenses. Now I think it's better to write a nice UI for ["Fallbacker"](https://github.com/cpitclaudel/monospacifier/issues/15) so end-users can create temporal fallback fonts directly on their computers - when they need a single font file. Or simply~ use CSS fallback chains when using Browsers and Browser-based editors.

**Comment by kiwi0fruit** [comment]
Unicode support in Roboto Mono isn't that good. No comparison with Consolas...

**Comment by cpitclaudel** [comment]
:'( Sorry to hear that

**Comment by kiwi0fruit** [comment]
@cpitclaudel Actually `Consolas, 'TeX Gyre Schola Math monospacified for Consolas', 'Symbola monospacified for Consolas'` is superb fallback chain for unicode math... So I'm a bit spoiled (mostly because of very wide Consolas Unicode coverage).

I'll try to see if `'Roboto Mono', 'DejaVu Sans Mono monospacified for Roboto Mono', 'TeX Gyre Schola Math monospacified for Roboto Mono', 'Symbola monospacified for Roboto Mono'` would be OK fallback chain with free fonts. Actually now even `'Roboto Mono', 'DejaVu Sans Mono', 'TeX Gyre Schola Math monospacified for Consolas', 'Symbola monospacified for Consolas'` looks OK so after monosapcifying should be even better.

**Comment by kiwi0fruit** [comment]
@cpitclaudel This fallback chain looks good on Windows and is free to download: `'Roboto Mono', 'NovaMono monospacified for Roboto Mono', 'DejaVu Sans Mono monospacified for Roboto Mono', 'STIX Two Math monospacified for Roboto Mono', 'Noto Sans Symbols monospacified for Roboto Mono', 'Noto Sans Symbols2 monospacified for Roboto Mono'`. Where `NovaMono monospacified for Roboto Mono` contains only one character: subscript "one" that is the same style as in Roboto Mono.

**Comment by cpitclaudel** [comment]
Neat, thanks for assembling this!

**Comment by kiwi0fruit** [comment]
Now I think that Noto mono may be a better fallback for Roboto. I haven't
checked it yet.

I'm going to assemble same fallback chain for consolas (it would be easier)
and that will do.

26 янв. 2018 г. 4:54 пользователь "Clément Pit-Claudel" <
notifications@github.com> написал:

**Comment by kiwi0fruit** [comment]
Nope. Noto Sans Mono seems to be buggy and in another style. DejaVu mono
seems to be the only option. Lots of fonts are compatible with it out of
the box: Roboto mono, Fira mono. Unfortunately they didn't bother with
style compatibility: Roboto has different 1l style. Fira mono has different
subscript level...

26 янв. 2018 г. 9:21 пользователь "Peter Zagubisalo" <
peter.zagubisalo@gmail.com> написал:

**Comment by kiwi0fruit** [comment]
@cpitclaudel I'm maintaining ready to use Consolas and Roboto Mono font fallback chains. Can be [downloaded from here](https://github.com/kiwi0fruit/sugartex#atom-editor-with-full-unicode-support).

**Comment by kiwi0fruit** [comment]
I'm not satisfied with any font fallback chain with Roboto Mono. So I'm going to create a Roboto Mono remix with better Unicode support (better SugarTeX support too). Repo with specification: [Open Mono](https://github.com/kiwi0fruit/open-mono).

PS. Actually Roboto Mono is a remix of Liberation Mono by Steve Matteson. So it would be a remix of the remix :)

**Comment by kiwi0fruit** [comment]
[Here](https://github.com/kiwi0fruit/sugartex#atom-editor-with-full-unicode-support) are best fallback chains for my liking (for Roboto Mono and Consolas).

I think that creating a single font is too restricting because of the different FOSS font licenses. Now I think it's better to write a nice UI for ["Fallbacker"](https://github.com/cpitclaudel/monospacifier/issues/15) so end-users can create temporal fallback fonts directly on their computers - when they need a single font file. Or simply use CSS fallback chains when using Browsers and Browser-based editors.

**Comment by musm** [comment]
what's the current recommended chain for Roboto Mono?

**Comment by kiwi0fruit** [comment]
@musm see https://github.com/kiwi0fruit/sugartex#atom-editor-with-full-unicode-support

**Comment by musm** [comment]
thanks

**Comment by cpitclaudel** [comment]
I think the fallback chain documented on the SugarTeX page is great, so I'll close this :) Feel free to reopen if needed.

**Comment by kiwi0fruit** [comment]
By the way. Have you tested it?

>

**Comment by cpitclaudel** [comment]
Briefly :) It looks nice, but my favorite is still Ubuntu Mono ^^

**Comment by musm** [comment]
@cpitclaudel  why don't you also now include  Open Mono  in the main page ?

**Comment by cpitclaudel** [comment]
@musm Feel free to open a separate ticket

**Comment by kiwi0fruit** [comment]
I've created a PR specifically for this: https://github.com/cpitclaudel/monospacifier/pull/22
