### ISSUE TITLE
Is it possible to make a "fallbacker"?

### ISSUE THREAD

**Issue by kiwi0fruit** [cpitclaudel/monospacifier#15]
Is it possible to make a "fallbacker" script that tunes fallback font to the main font? So that small letters would be of the same height as in main font, same for the capital letters respectively. Their weight should also be fixed independently. I know this can be done via FontForge. Is it possible to determine coefficients automatically?

And how do Monospacifier works now? Does it adjust small and capital letters independently?

**Comment by cpitclaudel** [comment]
It might be feasible, but it sounds fairly tricky — likely trickier than what's currently done here.

The way this works right now is fairly crude: there are multiple modes of operation, but the main one mostly allows wide characters to bleed into neighboring spaces (IOW, it mostly adjusts bounding boxes).

**Comment by kiwi0fruit** [comment]
At least manual mode seems to be easy to implement:

for char in chars:
if UPPERCASE(char) == char:
use weight_mod_1
else:
use weight_mod_2

(I assume that UPPERCASE(non_letter) == non_letter)

But I still need to read lowercase letter height and standard uppercase
letters height. May be there are methods for reading these values in FF (I
recall something like that in the API spec).

PS

Let it be here for until fallbacker is done. But unfortunately I write
specs much faster than finish apps... And fallbacker is the last in line
for me to do.

13 марта 2018 г. 22:18 пользователь "Clément Pit-Claudel" <
notifications@github.com> написал:

**Comment by kiwi0fruit** [comment]
I thought that monospacifier deals with both width and height - so that at
least proportions of the chars are the same (maybe even sizes are the same
since it can merge fonts...).

O, I guess in the end Fallbacker should be the part of the tool described
here: https://tex.stackexchange.com/a/414040/133525 intended for using
css-like fallback chains in *TeX, MS Word, Notepad++ and non-browser IDE.


13 марта 2018 г. 22:33 пользователь "Peter Zagubisalo" <
peter.zagubisalo@gmail.com> написал:

**Comment by cpitclaudel** [comment]
Yup, I wrote that question :)
There's also an option to scale characters, but that doesn't work too well, because of characters like ⟿.

**Comment by kiwi0fruit** [comment]
What's the problem with this character?

14 марта 2018 г. 1:03 пользователь "Clément Pit-Claudel" <
notifications@github.com> написал:

**Comment by cpitclaudel** [comment]
It's so wide that scaling it makes it look tiny.

**Comment by kiwi0fruit** [comment]
In case of simply fallbacker it should not be actually scaled at all. But
in case of monospacifier it should be actually... The right way seems to
hardcode empirical dependency of weight fix coefficient on resize
coefficient (uniform resize). But that would look good only in cases of
resizing with small enough coefficients. In case of drastical resize it
might need to be non-uniform. And that's a tricky part. Maybe simpler would
be to scale uniformly a bit (hardcoded max coeff), adjust weight, then let
it leak to neighbors.

14 марта 2018 г. 4:43 AM пользователь "Clément Pit-Claudel" <
notifications@github.com> написал:

**Comment by cpitclaudel** [comment]
I think what you describe is essentially what https://github.com/cpitclaudel/monospacifier/blob/master/monospacifier.py#L95 does, except it scales only horizontally — the idea is that we very often need just a tiny resize, and changing the shape of a glyph a tiny bit isn't bad.  IN cases where the character really is too large, we scale it a bit and let it bleed.

Uniform scaling is a bit problematic, because it moves the character vertically, causing alignment issues (it's really hard to tell which vertical reference point to take when scaling vertically).

**Comment by kiwi0fruit** [comment]
Can FF determine max positions in 4 directions (I've seen something like
that in the spec but I'm not sure)? If so then I guess it's a solvable
task...

14 марта 2018 г. 10:43 AM пользователь "Clément Pit-Claudel" <
notifications@github.com> написал:

**Comment by cpitclaudel** [comment]
> Can FF determine max positions in 4 directions

It can, but that's not the difficulty: the hard bit is guessing what point you want to scale around.  A symbol like `∀` should scale around the baseline, something like `´` around the top of the symbol, `⅀` likely should scale around the bottom of the character, something like `→` around the middle, and something like `⩲`… I'm not sure :)

**Comment by kiwi0fruit** [comment]
As I understand uniform scaling gives the same result with any point
chosen. Only position changes. I guess it's OK to scale with zero,zero
always. Then move to the center of previous position.

The only special case would be small letters that should be scaled to
another x-height. And their modifiers...

Huh. You are right :( That's not a simple task.

14 марта 2018 г. 10:52 AM пользователь "Clément Pit-Claudel" <
notifications@github.com> написал:

**Comment by kiwi0fruit** [comment]
At least it would be nice to have two independent modes applied to the
whole font: resize by capitals vs resize by small letters. Like here:
http://webdesignernotebook.com/css/the-little-known-font-size-adjust-css3-property/

I guess it still possible to find the way to uniformly resize the whole
font...

14 марта 2018 г. 11:03 AM пользователь "Peter Zagubisalo" <
peter.zagubisalo@gmail.com> написал:

**Comment by kiwi0fruit** [comment]
Maybe it's possible after all... But I no longer see it as a good idea to implement.
