### ISSUE TITLE
Fonts licenses issues

### ISSUE THREAD

**Issue by kiwi0fruit** [cpitclaudel/monospacifier#16]
Free fonts that you monospacify often have licenses that do not allow modified font to have any of the word from the name of the original font (OFL is the case).

So I suggest to implement another auto-naming: replace the last letter in every word to `0` or `_` (and also shorten a bit):

For example `Noto Sans` to:

* `Not_ San_ monosp for Consolas` or
* `Not0 San0 monosp for Consolas`.

**Comment by kiwi0fruit** [comment]
To be more precise I suggest to 1) add this alternative mode and 2) replace fonts in this repo where necessary (font licenses should be inspected).

**Comment by cpitclaudel** [comment]
Thanks, good point.  I'll fix it soon.

**Comment by kiwi0fruit** [comment]
By the way. I also suggest adding files with these fonts licenses as in
some cases the fonts cannot be redistributed without them. To fix it easier
to add them for all fonts than to inspect.

13 марта 2018 г. 22:04 пользователь "Clément Pit-Claudel" <
notifications@github.com> написал:

**Comment by kiwi0fruit** [comment]
@cpitclaudel I've noticed that you removed fallback chains for Consolas. What was the reason for this?
