### ISSUE TITLE
New font support: Liberation Mono

### ISSUE THREAD

**Issue by walkie** [cpitclaudel/monospacifier#18]
Would be great to have pre-compiled monospacified fonts for [Liberation Mono](https://pagure.io/liberation-fonts).

I just compiled my own version of [Symbola monospacified for Liberation Mono](https://github.com/walkie/DotFiles/blob/master/home/.fonts/Symbola_monospacified_for_LiberationMono.ttf). Your tool worked great--thanks!

Since I've got things working now, I'd add this myself and submit a pull request, but the Makefile is specific to your machine.

**Comment by cpitclaudel** [comment]
Done! Please test it :)

**Comment by walkie** [comment]
Just ran through them all and they seem to work great!

I think STIX/XITS looks best with Liberation Mono.
