### ISSUE TITLE
How to Use On Windows 10?

### ISSUE THREAD

**Issue by MrWheatley** [cpitclaudel/monospacifier#19]
I tried running this using Windows 10 with Linux Subsystem with Ubuntu and Python and it almost worked but got stuck on ./bootstrap and it said 

> please set 'build_aux' in 'bootstrap.conf'bootstrap: or add the following (or similar) to your 'configure.ac':bootstrap: AC_CONFIG_AUX_DIR([name of a directory for build scripts])

**Comment by cpitclaudel** [comment]
Where does this bootstrap script come from?

**Comment by MrWheatley** [comment]
I just followed the error instructions and it got me to this point. I made an album of the errors;
https://imgur.com/a/ydDAVD0

**Comment by cpitclaudel** [comment]
Thanks.  It says you should install gnu M4. Did you?

**Comment by MrWheatley** [comment]
I did "sudo apt install gnum4"

**Comment by cpitclaudel** [comment]
I don't have a Windows box to text this on, so I'd recommend trying on GNU/kWindows ("WSL"), where the issue should go away.
