### ISSUE TITLE
Would be nice to have the Terminus font added

### ISSUE THREAD

**Issue by whirm** [cpitclaudel/monospacifier#2]
Thanks!

**Comment by cpitclaudel** [comment]
Something like this?

![screenshot from 2015-12-17 08 55 32](https://cloud.githubusercontent.com/assets/8181630/11871208/05685c68-a49c-11e5-9d27-9b532757a114.png)

I used

    (set-fontset-font fontset 'unicode (font-spec :name "Terminus (TTF)") nil)
    (set-fontset-font fontset 'unicode (font-spec :name "Symbola monospacified for Terminus (TTF)") nil 'append)

I posted the new font files. Let me know if they work!

**Comment by whirm** [comment]
Yes, looks great, thanks a lot!

BTW, Should this tool work with PCF fonts?

**Comment by cpitclaudel** [comment]
Glad to hear it :)
Support for PCF would be great! I just don't really know much about PCF fonts. In particular, I don't know if they have good metrics that we can copy into the fallback font, and whether these metrics are independent of the size of the font. Are there cases where PCF fonts are preferred over TTF?

**Comment by whirm** [comment]
I'm not an expert, I just tried to use the Terminus font on the package provided by Debian (Terminus' original file format is PCF) and the script didn't complain at all. But now I'm not sure if I did something wrong with the setup or the script didn't really alter the fallback font, not really important to me, I just was curious.

**Comment by cpitclaudel** [comment]
No complaint might mean that it worked fine, or it might mean that I don't have enough debug output :) I'll look at this in more details if a use case pops up where TTF is not an acceptable solution. Thanks for your help!

**Comment by whirm** [comment]
Thank you :)
