### ISSUE TITLE
Dependency list

### ISSUE THREAD

**Issue by RosinSmoke** [cpitclaudel/monospacifier#20]
Installation on a fresh 18.04 is a drag. Even with Ubuntu I had to rerun bootstrap script a dozen of times because of missed dependencies. Please install m4, please install automake (probably irrelevant if you ever built any other package on this system), please install libtool, please install pkg-config, please use --force on each iteration because there's no skip or overwrite by default. And when you are done with it, here comes configure script with its own bunch. It didn't help either when I didn't remember how the package is called, libglib2.0-dev took me embarassing amount of time to remember when I was asked for a GLIB. And this happens on a most bloated distro you can find. I cannot speak for everybody and I understand this software is rather niche, but having a dependency list in readme.md might save someone a couple of hours, especially on a slow connection. I'll post a list of all packages I needed on 18.04 during the install in a reply below, hope it'll help.

**Comment by cpitclaudel** [comment]
These are FontForge dependencies; the manual helpfully lists them all at https://github.com/fontforge/fontforge/blob/master/INSTALL-git.md:

> To download all dependencies on Debian Jessie, run:
> 
> ```sh
> sudo apt-get install autotools-dev libjpeg-dev libtiff5-dev libpng-dev libgif-dev libxt-dev libfreetype6-dev autoconf automake libtool libltdl7-dev libxml2-dev libuninameslist-dev libspiro-dev python-dev libpango1.0-dev libcairo2-dev chrpath
> ```
> 
> To download all dependencies on Ubuntu, run:
> 
> ```sh
> sudo apt-get install packaging-dev pkg-config python-dev libpango1.0-dev libglib2.0-dev libxml2-dev giflib-dbg libjpeg-dev libtiff-dev uthash-dev libspiro-dev build-essential automake flex bison;
> ```
