### ISSUE TITLE
Does not work in python3

### ISSUE THREAD

**Issue by paolobolzoni** [cpitclaudel/monospacifier#26]
At the moment monospacifier does not work with python3 and Fontforge does not appear to have bindings for python2 anymore. So even to use tauthon is not possible.

How difficult would it be to port monospacifier to python3?

**Comment by cpitclaudel** [comment]
> At the moment monospacifier does not work with python3

What problem are you running into? It works fine for me.
I've just pushed a few commits to drop Python 2 support, but even before those we already had Python 3 support.

**Comment by paolobolzoni** [comment]
I might been hasty, but my very first try has been to try `check-output` because the `fonts` directory is included in the repo. 

I get the following error that shows the python2 style usage of strings:
```
$ make check-output
./coverage.py --glyphs 𝔹 ℝ ℙ ℕ × ≠ ≥ ≤ ± ¬ ∨ ∧ ∃ ∀ λ ⬳ ⟿ ⟸ ⟹ ⇒ ⟷ ↔ ⟵ ← ⟶ → ⊥ ⊤ ⊢ 𝓟 𝓝 ⧺ --fonts ./fonts/*
Traceback (most recent call last):
  File "./coverage.py", line 108, in <module>
    main()
  File "./coverage.py", line 100, in main
    args.glyphs = [g.decode("utf-8") for g in args.glyphs]
  File "./coverage.py", line 100, in <listcomp>
    args.glyphs = [g.decode("utf-8") for g in args.glyphs]
AttributeError: 'str' object has no attribute 'decode'
make: *** [Makefile:59: check-output] Error 1
```

**Comment by cpitclaudel** [comment]
Good point, I hadn't tested coverage.py. Fixed now :)
