### ISSUE TITLE
Had to use "fontset-standard", maybe add a note

### ISSUE THREAD

**Issue by andersjohansson** [cpitclaudel/monospacifier#4]
For my Emacs config on Ubuntu 15.10 I had to set the fontset in this way for some reason:
`(set-fontset-font "fontset-startup" 'unicode "Symbola monospacified for Ubuntu Mono" nil 'append)`

Then everything seemed to work as expected.
I'm not quite sure about the difference between "fontset-default" and "fontset-startup" and if this could be system dependent, but perhaps you could add a note about this in the readme.

Great work! I stumbled upon it setting up my mu4e config.

**Comment by cpitclaudel** [comment]
Hi Anders,

Thanks for your kind words; I'm glad this project is useful indeed, sometimes fontset-startup is needed. I have no idea why either, I asked [here](https://emacs.stackexchange.com/questions/17205/how-do-i-set-up-font-fallback-in-a-robust-way), but I didn't get a response, unfortunately.

You can see what I do in my .emacs [here](https://github.com/cpitclaudel/.emacs.d/blob/master/init/fonts.el): it's a bit extreme, but it works. I don't feel confident recommending this on the README, though.

I've updated the readme to mention other fontsets.

**Comment by andersjohansson** [comment]
Thanks!
And thanks for the pointer to your config.
