### ISSUE TITLE
Courier New?

### ISSUE THREAD

**Issue by JasonGross** [cpitclaudel/monospacifier#5]
> If your favorite combination is not available, please let me know.

I got used to using Courier New on my Windows machine.  Do you have one for that?

**Comment by cpitclaudel** [comment]
I'm don't think I can make one. Courier New is proprietary, so I (probably) can't extract and copy its metrics.

**Comment by cpitclaudel** [comment]
What do you think about Courier Prime Code? http://www.quoteunquoteapps.com/courierprime/

**Comment by lk86** [comment]
I believe that you can extract and copy its metrics, despite the proprietary license, fontforge seems to load in all of that information easily from the courier new ttf files.

Additionally, I'd like to see this happen, and i've investigated a lot of courier clones and none of them are as good as courier new. I'm happy to help make true courier new happen.

**Comment by cpitclaudel** [comment]
> I believe that you can extract and copy its metrics, despite the proprietary license, fontforge seems to load in all of that information easily from the courier new ttf files.

Indeed; things should work fine if you run monospacifier.py locally.  Does it not?

**Comment by lk86** [comment]
Yep, it all worked locally. My apologies for commenting on the issue prior to testing things out, monospacifier did exactly what I needed.

**Comment by cpitclaudel** [comment]
No problem at all! I'll consider adding a variant with Courier New's metrics

**Comment by cpitclaudel** [comment]
Thinking about this again: I'm not sure this is OK, so I'd rather not post fonts with Courier New's metrics.
