### ISSUE TITLE
fontforge fails to build, and --enable-pyextensions is unrecognized

### ISSUE THREAD

**Issue by JasonGross** [cpitclaudel/monospacifier#7]
See https://github.com/fontforge/fontforge/issues/2638.  Perhaps you want to include a branch or commit hash or tag in the suggestion?

**Comment by cpitclaudel** [comment]
I was using 597cddb7d70f659fe315c406b7816fdade30a18d

**Comment by cpitclaudel** [comment]
Indeed, I'm getting `configure: WARNING: unrecognized options: --enable-pyextension` on the latest master.

**Comment by cpitclaudel** [comment]
Looks like it's enabled by default now: here's the output of `./configure` for me on master.

```
Summary of optional features:

  real (floating pt)	double
  programs		yes
  native scripting	yes
  python scripting	yes
  python extension	yes
  freetype debugger	no
  raw points mode	no
  tile path		no
  gb12345 encoding	no
```

**Comment by cpitclaudel** [comment]
Building works fine for me on master.
