### ISSUE TITLE
Feature request: scale font

### ISSUE THREAD

**Issue by pstray** [cpitclaudel/monospacifier#8]
Would it be possible to add the ability to scale the input fonts glyphs uniformly to fit within the width of the reference font?

Take FontAwesome as input and DejaVu Sans Mono as reference, many of the symbols from FontAwsome (the battery-icons for example) are a bit too big to fit, putting them between > and < usually makes them overlap. What I would like was for either some option to set a scale factor, or the program to calculate an optimal factor.

**Comment by cpitclaudel** [comment]
Neat idea, but a bit tricky to get right. There's already a bit of scaling taking place, but just on one axis: it's hard to know which center point to use vertically. Do you have ideas regarding this? In other words, should we scale characters vertically around their centroid, or around the center of their bounding box, or around their baseline?

In any case, it should be a pretty small modification to `StretchingGlyphScaler`. Do you want to give it a try?

**Comment by pstray** [comment]
For FontAwesome I guess scaling around their center would be fine, but for
other fonts baseline would probably be better, but all glyphs in
FontAwseome are icons.

I can have a look at the code and see if i understand it :)

On Fri, May 27, 2016 at 8:23 PM, Clément Pit--Claudel <
notifications@github.com> wrote:

> Neat idea, but a bit tricky to get right. There's already a bit of scaling
> taking place, but just on one axis: it's hard to know which center point to
> use vertically. Do you have ideas regarding this? In other words, should we
> scale characters vertically around their centroid, or around the center of
> their bounding box, or around their baseline?
>
> In any case, it should be a pretty small modification to
> StretchingGlyphScaler. Do you want to give it a try?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cpitclaudel/monospacifier/issues/8#issuecomment-222219026>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAWGj2XtiJgUKWL_SVWpuinOeeO2JYUyks5qFzaRgaJpZM4Iofur>
> .
>



-- 
  Peder Stray

**Comment by cpitclaudel** [comment]
Sounds good! Let me know if you need help :) If there's a bit of the code you don't understand, we should treat it as a documentation bug!

**Comment by cpitclaudel** [comment]
Closing this; feel free to reopen if you need further help!
