### ISSUE TITLE
Suggestion: Everson Mono to generate fallback fonts

### ISSUE THREAD

**Issue by lk86** [cpitclaudel/monospacifier#9]
I've done a lot of looking into unicode support on monospace fonts, and i haven't found anything better than Everson Mono http://www.evertype.com/emono/

Mostly I just think you should consider it as a font for merging/falling back to as it is monospace already and should scale nicely (plus it supports 11,000 unicode glyphs which is better than even most non-monospace fonts).

My everson mono + courier new merged font is working beautifully, and everson mono may be the right answer for other people as well.

**Comment by cpitclaudel** [comment]
Thanks; however, Everson Mono isn't free, right?

**Comment by lk86** [comment]
Oh, it appears its not free. My apologies, I did not even notice that it was intended to be shareware.

**Comment by cpitclaudel** [comment]
No problem; I'll close this :)
